export const navLists = [
    {
      name: "首页",
      icon: "icon-shouye",
      path: "HomePage",
      label: "home",
      order: 0,
      isExit: true,
    },
    {
      name: "信息查询",
      icon: "icon--zhuantishujufenxi",
      path: "FingerprintSearch",
      label: "information-search",
      order: 1,
      isExit: true,
      children: [
        {
          name: "指纹图谱查询",
          icon: "icon-zhiwenshibie",
          path: "FingerprintSearch",
          label: "fingerprint",
          order: 0,
          isExit: true,
        },
        {
          name: "SNP标记查询",
          icon: "icon-icon4",
          path: "SNPMarkerSearch",
          label: "snpmarker",
          order: 1,
          isExit: true,
        },
        {
          name: "品种相似度分析",
          icon: "icon-shujufenxi",
          path: "VarietySimilarityAnalysis",
          label: "varietysimilarityanalysis",
          order: 2,
          isExit: true,
        },
        {
          name: "品种差异分析",
          icon: "icon-shujufenxi",
          path: "VarietyDifferenceAnalysis",
          label: "varietydifferenceanalysis",
          order: 3,
          isExit: true,
        },
        {
          name: "杂交亲本预测",
          icon: "icon-shujufenxi",
          path: "PredictionOfHybridParents",
          label: "predictionofhybridparents",
          order: 4,
          isExit: true,
        },
      ],
    },
    {
      name: "账户信息管理",
      icon: "icon-a-97_qiyezhanghuguanli",
      path: "AccountInformationManagement",
      label: "account",
      order: 2,
      isExit: true,
      children: [
        {
          name: "企业账户管理",
          icon: "icon-jichuxinxiguanli",
          path: "AccountInformationManagement",
          label: "enterprise-management",
          order: 0,
          isExit: true,
        },
        {
          name: "用户管理",
          icon: "icon-jichuxinxiguanli",
          path: "UserManagement",
          label: "user-management",
          order: 1,
          isExit: true,
        },
        {
          name: "角色管理",
          icon: "icon-jichuxinxiguanli",
          path: "RoleManagement",
          label: "role-management",
          order: 2,
          isExit: true,
        },
      ],
    },
  ]